language: scala

scala:
  - 2.12.2
  - 2.11.11

script:
#  - sbt clean test
  - sbt ++$TRAVIS_SCALA_VERSION clean test

jdk:
  - oraclejdk8

env:
  global:
    - secure: "Aza26mYVHkU+AR1DbBNj/QTP51s5aOCLgRUTC+mTjILAdVYmQWaHDdfQzEqRJDtfAiPwhUruhaY5ujpr2C3E4RPoe7oOR9c/bJiiBSMRyyOVf51kI3/G5Mp4hHRm+XwPgS7CygbTAfurLWt+w8hpS4rif693RETB5oczlkGYdom4UvQIPoFeP4Sr494IZnlYoYxgXMZw5xQlLVVmAGT9AA+CuauzS+4DT01UioPno5+kRb37klyyQJG8SqdV0lezDAtQG+majgkkY/gCJMWQqaVY95SCCWnqGvUvj6oTBkRj+edsprmx3sCMF0MQLnO/6zvQCpvn0yrTsimi2BMWRy9XsQBSXH48ROQRd/DgjqcZcSe0esWYMGGzujXPSAXSCDC7Ng/th1I1rWfHqE730L4IARSb3mhDZ7KqXJuszX/JJpBpW3AOElECJQNgMh5Gppu6e8JFeoTf8GEsI5Bt8vbF30H61lzm9UUG0jmwcXgKvc1LOItGZZuHAn4jErPH89FSRkBTlkFiZUxiD7sYydt4usgO4N8B3H0XIIhHAgBeL9BR4X/YoIx5OjvPPGDoSoIJJBgDiEHQyKdaU4S6XkWVFvXJ8WgBB3XEvD2iw7wVKXtS9a1tjv/ow+KbCIiyBxhtBvZhMX/2WnQxAgzcxe2feXg6kVzcj7ov2jrD6yw="
    - secure: "feoazeAprnOCl9oVjSDUz/4Z9IEX7EdlWRS5eK5L4XaVG4WQkBk5htpFC2feA9XNvesSLGZenmd3dOSFfReUJkhR3KYRCiTZMkncgxBMLc9E4qEf9J76jP5p5wfNl0ut+fowd9ktMcREzHDtlZC7t/ChL7FDCTKfqGvhRxTMc+l9Lk2nQTJ1Q9WVmF0RpS/3P7XrER373h9LhQvUFoHm8mR4vmQGmFZeveEy45CWOx6QB4jhAENsCzfuuBOg3XVN8OQHlFKfbvjV5nSW9nxAbmCF4FG5kWc34WzZ/vjTOYxP0u5EG4SgjdOhy8yqnG0B0PIxJf9ROoL7xmdi/w0bOIR0khonSa83xg/vYa68zT9kGcVdr8agFVT4koxvpn126t5mkWMc8DTd9+KAlJgP3LuXJfG9eW/IHt5MnjUg2pDTHXJMpaAphPHIAqcCCAFMESa8EGXt6sdME9FMbJTRsSoko5InUAsgZVgxo6bNcLfksH4z4O9MHiGLKRkOkK+nz12draaahVnz0fi6eNGJIv1n6La/fI7WY1TJeHdvXd/DRlnvJhvSAncmzp6hfQKf+VeFv/3GiK/ZhtKEHK1JyYVmQ9lFAu52RVt0K+A4p2UbkYDxXeEEPuHub7+twjSjQUrkLehB28uQjo37xaMSpj6So/l0mUYrHOim/TPSgSw="

after_success:
  - "[[ $TRAVIS_BRANCH == \"master\" ]] && { sbt ++$TRAVIS_SCALA_VERSION publish; };"
